In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder

In [2]:
file_path = r"D:\Aditya\Downloads_D\AI_Engineer\Machine Learning\Datasets\encoding techniques\Ecommerce_Customer_Data.csv"

In [3]:
df = pd.read_csv(file_path)
df

   Customer ID     City Feedback Rating Payment Method Return Customer
0          101  Chicago            Good    Credit Card             Yes
1          102    Miami       Excellent         PayPal             Yes
2          103  Chicago            Poor     Debit Card              No
3          104  Seattle         Neutral    Credit Card              No
4          105    Miami            Good     Debit Card             Yes
5          106  Seattle       Excellent         PayPal             Yes

In [4]:
df_copy = df.copy()
df_copy_sk = df.copy()

## Label Encoding (for Ordinal Data)

### Using 'map' funtion

In [ ]:
feedback_map = {
    'Poor' : 0,
    'Neutral' : 1,
    'Good' : 2,
    'Excellent' : 3
}

df_copy['Feedback Rating'] = df_copy['Feedback Rating'].map(feedback_map)

df_copy['Return Customer'] = df_copy['Return Customer'].map({'Yes': 0, 'No' : 1})
df_copy

### using scikit-learn

In [ ]:
feedback_order = [['Poor', 'Neutral', 'Good', 'Excellent']]
ord_encoder = OrdinalEncoder(categories=feedback_order)

df_copy_sk['Feedback Rating'] = ord_encoder.fit_transform(df_copy_sk[['Feedback Rating']])
df_copy_sk

In [ ]:
label_encoder = LabelEncoder()
df_copy_sk['Return Customer'] = label_encoder.fit_transform(df_copy_sk['Return Customer'])
df_copy_sk

## ONE-HOT ENCODING (For Nominal Data)

In [5]:
df_copy = pd.get_dummies(df_copy,columns=['City', 'Payment Method'], dtype=int)
df_copy

,Customer ID,Feedback Rating,Return Customer,City_Chicago,City_Miami,City_Seattle,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_PayPal
0,101,Good,Yes,1,0,0,1,0,0
1,102,Excellent,Yes,0,1,0,0,0,1
2,103,Poor,No,1,0,0,0,1,0
3,104,Neutral,No,0,0,1,1,0,0
4,105,Good,Yes,0,1,0,0,1,0
5,106,Excellent,Yes,0,0,1,0,0,1

### Using scikit-learn

In [7]:
# sparse_output=False ensures it returns a readable matrix of 1s and 0s
oh_encoder = OneHotEncoder(sparse_output=False)

# Fit and transform the two nominal columns
encoder_matrix = oh_encoder.fit_transform(df[['City', 'Payment Method']])

# Scikit-learn returns a raw Numpy array, so we need to get the new column names...
new_columns_name = oh_encoder.get_feature_names_out(['City', 'Payment Method'])

# convert that array back into a Pandas DataFrame
encoded_df = pd.DataFrame(encoder_matrix,columns=new_columns_name)
encoded_df

,City_Chicago,City_Miami,City_Seattle,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_PayPal
0,1.0,0.0,0.0,1.0,0.0,0.0
1,0.0,1.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,1.0,1.0,0.0,0.0
4,0.0,1.0,0.0,0.0,1.0,0.0
5,0.0,0.0,1.0,0.0,0.0,1.0

## Processed Data

In [8]:
df_copy

,Customer ID,Feedback Rating,Return Customer,City_Chicago,City_Miami,City_Seattle,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_PayPal
0,101,Good,Yes,1,0,0,1,0,0
1,102,Excellent,Yes,0,1,0,0,0,1
2,103,Poor,No,1,0,0,0,1,0
3,104,Neutral,No,0,0,1,1,0,0
4,105,Good,Yes,0,1,0,0,1,0
5,106,Excellent,Yes,0,0,1,0,0,1

In [9]:
final_df_sk = pd.concat([df_copy_sk,encoded_df], axis=1)

# Drop the old text columns that we just one-hot encoded
final_df_sk = final_df_sk.drop(['City', 'Payment Method'], axis=1)

final_df_sk

,Customer ID,Feedback Rating,Return Customer,City_Chicago,City_Miami,City_Seattle,Payment Method_Credit Card,Payment Method_Debit Card,Payment Method_PayPal
0,101,Good,Yes,1.0,0.0,0.0,1.0,0.0,0.0
1,102,Excellent,Yes,0.0,1.0,0.0,0.0,0.0,1.0
2,103,Poor,No,1.0,0.0,0.0,0.0,1.0,0.0
3,104,Neutral,No,0.0,0.0,1.0,1.0,0.0,0.0
4,105,Good,Yes,0.0,1.0,0.0,0.0,1.0,0.0
5,106,Excellent,Yes,0.0,0.0,1.0,0.0,0.0,1.0